import Foundation

// MARK: - LanguageManager

@Observable
final class LanguageManager {

    private(set) var language: String

    static let supported: [(code: String, displayName: String)] = [
        ("es", "Español"),
        ("en", "English"),
        ("fr", "Français"),
        ("de", "Deutsch"),
        ("zh", "中文"),
        ("it", "Italiano"),
        ("ca", "Català"),
    ]

    var locale: Locale {
        Locale(identifier: language == "zh" ? "zh-Hans" : language)
    }

    init() {
        language = UserDefaults.standard.string(forKey: "appLanguage") ?? "es"
    }

    func setLanguage(_ code: String) {
        language = code
        UserDefaults.standard.set(code, forKey: "appLanguage")
    }

    subscript(_ key: String) -> String {
        Translations.all[language]?[key] ?? Translations.all["es"]![key] ?? key
    }
}

// MARK: - Translations

private enum Translations {

    static let all: [String: [String: String]] = [
        "es": es, "en": en, "fr": fr, "de": de, "zh": zh, "it": it, "ca": ca,
    ]

    // MARK: Español
    static let es: [String: String] = [
        // Tabs
        "tab.home": "Inicio",
        "tab.week": "Semana",
        "tab.records": "Registros",
        "tab.charts": "Gráficos",
        "tab.settings": "Ajustes",
        // Dashboard
        "dash.timer": "Cronómetro",
        "dash.save": "Guardar",
        "dash.start": "Iniciar",
        "dash.current_week": "Semana actual",
        "dash.by_client": "Por cliente / departamento",
        "dash.no_hours": "Aún no has registrado horas esta semana.",
        "dash.assigned": "Asignadas",
        "dash.worked": "Trabajadas",
        "dash.remaining": "Restantes",
        "dash.excess": "Exceso",
        "dash.progress": "Progreso",
        "dash.record_hours": "Registrar horas",
        // Week view
        "week.summary": "Resumen",
        "week.calendar": "Calendario",
        "week.this_week": "Esta semana",
        "week.back_to_today": "Volver a hoy",
        "week.no_records_day": "Sin registros para este día.",
        "week.connect_google": "Conecta Google Calendar",
        "week.google_desc": "Visualiza tus eventos junto con tus horas de trabajo sin salir de la app.",
        "week.connect_google_btn": "Conectar con Google",
        "week.loading": "Cargando eventos…",
        "week.readonly": "Solo lectura",
        "week.readonly_desc": "Amplía los permisos para crear y editar eventos.",
        "week.expand": "Ampliar",
        "week.all_day": "Todo el día",
        "week.all_day_short": "Todo\nel día",
        "week.disconnect": "Desconectar Google Calendar",
        "week.no_events": "Sin eventos esta semana.",
        // Calendar event
        "cal.detail": "Detalle del evento",
        "cal.close": "Cerrar",
        "cal.edit": "Editar",
        "cal.delete": "Eliminar evento",
        "cal.new": "Nuevo evento",
        "cal.edit_title": "Editar evento",
        "cal.title_placeholder": "Título del evento",
        "cal.cancel": "Cancelar",
        "cal.create": "Crear",
        "cal.save": "Guardar",
        "cal.start": "Inicio",
        "cal.end": "Fin",
        "cal.date": "Fecha",
        // Time entries
        "entries.empty_title": "Sin registros",
        "entries.empty_message": "Empieza registrando las horas que trabajas cada día.",
        "entries.record": "Registrar horas",
        "entries.delete": "Borrar",
        "entries.all_clients": "Todos los clientes",
        "entries.all_projects": "Todos los proyectos",
        "entries.clear_filters": "Quitar filtros",
        "entries.unassigned": "Sin asignar",
        // Entry form
        "form.date": "Fecha",
        "form.day": "Día",
        "form.hours": "Horas trabajadas",
        "form.client": "Cliente / Departamento",
        "form.create_client": "Crea primero un cliente en Ajustes.",
        "form.no_client": "Sin asignar",
        "form.project": "Proyecto",
        "form.no_project": "Sin proyecto",
        "form.comment": "Comentario (opcional)",
        "form.comment_hint": "Notas sobre el trabajo…",
        "form.delete_entry": "Eliminar registro",
        "form.new": "Nuevo registro",
        "form.edit": "Editar registro",
        "form.cancel": "Cancelar",
        "form.save": "Guardar",
        "form.delete": "Eliminar",
        "form.irreversible": "Esta acción no se puede deshacer.",
        "form.client_picker": "Cliente",
        "form.project_picker": "Proyecto",
        // Settings
        "settings.organization": "Organización",
        "settings.clients": "Clientes / Departamentos",
        "settings.projects": "Proyectos",
        "settings.hours_section": "Horas",
        "settings.weekly_hours": "Horas semanales",
        "settings.data": "Datos",
        "settings.export": "Exportar registros (CSV)",
        "settings.support": "Soporte",
        "settings.rate": "Valorar la app",
        "settings.suggest": "Enviar sugerencia",
        "settings.version": "Versión",
        "settings.privacy": "Tus datos se guardan únicamente en este dispositivo.",
        "settings.language": "Idioma",
        "settings.language_section": "Idioma",
        // Weekly hours
        "whours.title": "Horas semanales",
        "whours.total": "Total semanal",
        "whours.per_week": "Horas/semana",
        "whours.daily": "Objetivo diario",
        "whours.auto": "Auto",
        "whours.distribution": "Reparto del presupuesto",
        "whours.assigned": "Asignadas a clientes",
        "whours.available": "Disponibles",
        "whours.overassigned": "Has asignado más horas de las disponibles.",
        "whours.no_assigned": "Sin asignar",
        "whours.footer": "En 0, se calcula automáticamente como el total semanal ÷ 5 días.",
        "whours.by_client": "Por cliente / departamento",
        // Clients
        "clients.title": "Clientes",
        "clients.new": "Nuevo cliente",
        "clients.edit": "Editar cliente",
        "clients.name": "Nombre",
        "clients.color": "Color identificativo",
        "clients.placeholder": "Ej. Cliente Acme / Marketing",
        "clients.save": "Guardar",
        "clients.cancel": "Cancelar",
        "clients.empty_title": "Sin clientes",
        "clients.empty_message": "Crea tu primer cliente o departamento para organizar tus horas.",
        "clients.add": "Nuevo cliente",
        "clients.projects_one": "proyecto",
        "clients.projects_many": "proyectos",
        // Projects
        "projects.title": "Proyectos",
        "projects.new": "Nuevo proyecto",
        "projects.edit": "Editar proyecto",
        "projects.name": "Nombre",
        "projects.clients_section": "Clientes / Departamentos",
        "projects.description": "Descripción (opcional)",
        "projects.description_hint": "Detalles del proyecto…",
        "projects.weekly_hours": "Horas semanales asignadas",
        "projects.color": "Color identificativo",
        "projects.save": "Guardar",
        "projects.cancel": "Cancelar",
        "projects.empty_title": "Sin proyectos",
        "projects.empty_no_clients": "Crea primero un cliente y luego asígnale proyectos.",
        "projects.empty_message": "Crea tu primer proyecto y asígnalo a un cliente.",
        "projects.add": "Nuevo proyecto",
        "projects.no_client": "Sin cliente",
        "projects.per_week": "Horas/semana",
        "projects.create_client_first": "Crea primero un cliente en Ajustes.",
        "projects.selected": "Seleccionados:",
        "projects.placeholder": "Ej. Rediseño web",
        // Statistics
        "stats.no_data": "Sin datos",
        "stats.no_data_message": "No hay registros en este periodo.",
        "stats.hours_by": "Horas por",
        "stats.client": "Cliente",
        "stats.project": "Proyecto",
        "stats.evolution": "Evolución de horas trabajadas",
        "stats.current_period": "Periodo actual",
        // Periods
        "period.week": "Semana",
        "period.month": "Mes",
        "period.year": "Año",
        "period.picker": "Periodo",
        // Language settings
        "lang.title": "Idioma",
        // Common dynamic
        "common.missing_format": "Faltan {0}",
    ]

    // MARK: English
    static let en: [String: String] = [
        "tab.home": "Home", "tab.week": "Week", "tab.records": "Records",
        "tab.charts": "Charts", "tab.settings": "Settings",
        "dash.timer": "Stopwatch", "dash.save": "Save", "dash.start": "Start",
        "dash.current_week": "Current week",
        "dash.by_client": "By client / department",
        "dash.no_hours": "You haven't logged any hours this week yet.",
        "dash.assigned": "Assigned", "dash.worked": "Worked",
        "dash.remaining": "Remaining", "dash.excess": "Excess",
        "dash.progress": "Progress", "dash.record_hours": "Log hours",
        "week.summary": "Summary", "week.calendar": "Calendar",
        "week.this_week": "This week", "week.back_to_today": "Back to today",
        "week.no_records_day": "No records for this day.",
        "week.connect_google": "Connect Google Calendar",
        "week.google_desc": "View your events alongside your work hours without leaving the app.",
        "week.connect_google_btn": "Connect with Google",
        "week.loading": "Loading events…",
        "week.readonly": "Read only",
        "week.readonly_desc": "Expand permissions to create and edit events.",
        "week.expand": "Expand", "week.all_day": "All day",
        "week.all_day_short": "All\nday",
        "week.disconnect": "Disconnect Google Calendar",
        "week.no_events": "No events this week.",
        "cal.detail": "Event detail", "cal.close": "Close", "cal.edit": "Edit",
        "cal.delete": "Delete event", "cal.new": "New event",
        "cal.edit_title": "Edit event", "cal.title_placeholder": "Event title",
        "cal.cancel": "Cancel", "cal.create": "Create", "cal.save": "Save",
        "cal.start": "Start", "cal.end": "End", "cal.date": "Date",
        "entries.empty_title": "No records",
        "entries.empty_message": "Start logging the hours you work each day.",
        "entries.record": "Log hours", "entries.delete": "Delete",
        "entries.all_clients": "All clients", "entries.all_projects": "All projects",
        "entries.clear_filters": "Clear filters", "entries.unassigned": "Unassigned",
        "form.date": "Date", "form.day": "Day", "form.hours": "Hours worked",
        "form.client": "Client / Department",
        "form.create_client": "Create a client in Settings first.",
        "form.no_client": "Unassigned", "form.project": "Project",
        "form.no_project": "No project", "form.comment": "Comment (optional)",
        "form.comment_hint": "Notes about the work…",
        "form.delete_entry": "Delete record", "form.new": "New record",
        "form.edit": "Edit record", "form.cancel": "Cancel",
        "form.save": "Save", "form.delete": "Delete",
        "form.irreversible": "This action cannot be undone.",
        "form.client_picker": "Client", "form.project_picker": "Project",
        "settings.organization": "Organization",
        "settings.clients": "Clients / Departments",
        "settings.projects": "Projects", "settings.hours_section": "Hours",
        "settings.weekly_hours": "Weekly hours", "settings.data": "Data",
        "settings.export": "Export records (CSV)", "settings.support": "Support",
        "settings.rate": "Rate the app", "settings.suggest": "Send suggestion",
        "settings.version": "Version",
        "settings.privacy": "Your data is stored only on this device.",
        "settings.language": "Language", "settings.language_section": "Language",
        "whours.title": "Weekly hours", "whours.total": "Weekly total",
        "whours.per_week": "Hours/week", "whours.daily": "Daily target",
        "whours.auto": "Auto", "whours.distribution": "Budget distribution",
        "whours.assigned": "Assigned to clients", "whours.available": "Available",
        "whours.overassigned": "You've assigned more hours than available.",
        "whours.no_assigned": "Unassigned",
        "whours.footer": "At 0, calculated automatically as weekly total ÷ 5 days.",
        "whours.by_client": "By client / department",
        "clients.title": "Clients", "clients.new": "New client",
        "clients.edit": "Edit client", "clients.name": "Name",
        "clients.color": "Identifying colour",
        "clients.placeholder": "E.g. Acme Client / Marketing",
        "clients.save": "Save", "clients.cancel": "Cancel",
        "clients.empty_title": "No clients",
        "clients.empty_message": "Create your first client or department to organise your hours.",
        "clients.add": "New client",
        "clients.projects_one": "project", "clients.projects_many": "projects",
        "projects.title": "Projects", "projects.new": "New project",
        "projects.edit": "Edit project", "projects.name": "Name",
        "projects.clients_section": "Clients / Departments",
        "projects.description": "Description (optional)",
        "projects.description_hint": "Project details…",
        "projects.weekly_hours": "Assigned weekly hours",
        "projects.color": "Identifying colour",
        "projects.save": "Save", "projects.cancel": "Cancel",
        "projects.empty_title": "No projects",
        "projects.empty_no_clients": "Create a client first, then assign projects to it.",
        "projects.empty_message": "Create your first project and assign it to a client.",
        "projects.add": "New project", "projects.no_client": "No client",
        "projects.per_week": "Hours/week",
        "projects.create_client_first": "Create a client in Settings first.",
        "projects.selected": "Selected:",
        "projects.placeholder": "E.g. Website redesign",
        "stats.no_data": "No data",
        "stats.no_data_message": "No records in this period.",
        "stats.hours_by": "Hours by", "stats.client": "Client",
        "stats.project": "Project",
        "stats.evolution": "Work hours evolution",
        "stats.current_period": "Current period",
        "period.week": "Week", "period.month": "Month", "period.year": "Year",
        "period.picker": "Period",
        "lang.title": "Language",
        "common.missing_format": "{0} remaining",
    ]

    // MARK: Français
    static let fr: [String: String] = [
        "tab.home": "Accueil", "tab.week": "Semaine", "tab.records": "Registres",
        "tab.charts": "Graphiques", "tab.settings": "Paramètres",
        "dash.timer": "Chronomètre", "dash.save": "Enregistrer",
        "dash.start": "Démarrer", "dash.current_week": "Semaine actuelle",
        "dash.by_client": "Par client / département",
        "dash.no_hours": "Vous n'avez pas encore enregistré d'heures cette semaine.",
        "dash.assigned": "Assignées", "dash.worked": "Travaillées",
        "dash.remaining": "Restantes", "dash.excess": "Excès",
        "dash.progress": "Progrès", "dash.record_hours": "Enregistrer des heures",
        "week.summary": "Résumé", "week.calendar": "Calendrier",
        "week.this_week": "Cette semaine",
        "week.back_to_today": "Retour à aujourd'hui",
        "week.no_records_day": "Aucun enregistrement pour ce jour.",
        "week.connect_google": "Connecter Google Calendar",
        "week.google_desc": "Visualisez vos événements avec vos heures de travail sans quitter l'app.",
        "week.connect_google_btn": "Connecter avec Google",
        "week.loading": "Chargement des événements…",
        "week.readonly": "Lecture seule",
        "week.readonly_desc": "Développez les autorisations pour créer et modifier des événements.",
        "week.expand": "Développer", "week.all_day": "Toute la journée",
        "week.all_day_short": "Toute\nla journée",
        "week.disconnect": "Déconnecter Google Calendar",
        "week.no_events": "Aucun événement cette semaine.",
        "cal.detail": "Détail de l'événement", "cal.close": "Fermer",
        "cal.edit": "Modifier", "cal.delete": "Supprimer l'événement",
        "cal.new": "Nouvel événement", "cal.edit_title": "Modifier l'événement",
        "cal.title_placeholder": "Titre de l'événement",
        "cal.cancel": "Annuler", "cal.create": "Créer", "cal.save": "Enregistrer",
        "cal.start": "Début", "cal.end": "Fin", "cal.date": "Date",
        "entries.empty_title": "Aucun enregistrement",
        "entries.empty_message": "Commencez à enregistrer les heures que vous travaillez chaque jour.",
        "entries.record": "Enregistrer des heures", "entries.delete": "Supprimer",
        "entries.all_clients": "Tous les clients",
        "entries.all_projects": "Tous les projets",
        "entries.clear_filters": "Effacer les filtres",
        "entries.unassigned": "Non assigné",
        "form.date": "Date", "form.day": "Jour",
        "form.hours": "Heures travaillées",
        "form.client": "Client / Département",
        "form.create_client": "Créez d'abord un client dans Paramètres.",
        "form.no_client": "Non assigné", "form.project": "Projet",
        "form.no_project": "Aucun projet",
        "form.comment": "Commentaire (optionnel)",
        "form.comment_hint": "Notes sur le travail…",
        "form.delete_entry": "Supprimer l'enregistrement",
        "form.new": "Nouvel enregistrement",
        "form.edit": "Modifier l'enregistrement",
        "form.cancel": "Annuler", "form.save": "Enregistrer",
        "form.delete": "Supprimer",
        "form.irreversible": "Cette action est irréversible.",
        "form.client_picker": "Client", "form.project_picker": "Projet",
        "settings.organization": "Organisation",
        "settings.clients": "Clients / Départements",
        "settings.projects": "Projets", "settings.hours_section": "Heures",
        "settings.weekly_hours": "Heures hebdomadaires",
        "settings.data": "Données",
        "settings.export": "Exporter les enregistrements (CSV)",
        "settings.support": "Assistance", "settings.rate": "Évaluer l'app",
        "settings.suggest": "Envoyer une suggestion",
        "settings.version": "Version",
        "settings.privacy": "Vos données sont stockées uniquement sur cet appareil.",
        "settings.language": "Langue", "settings.language_section": "Langue",
        "whours.title": "Heures hebdomadaires",
        "whours.total": "Total hebdomadaire",
        "whours.per_week": "Heures/semaine",
        "whours.daily": "Objectif quotidien",
        "whours.auto": "Auto",
        "whours.distribution": "Répartition du budget",
        "whours.assigned": "Assignées aux clients",
        "whours.available": "Disponibles",
        "whours.overassigned": "Vous avez attribué plus d'heures que disponibles.",
        "whours.no_assigned": "Non assigné",
        "whours.footer": "À 0, calculé automatiquement comme le total hebdomadaire ÷ 5 jours.",
        "whours.by_client": "Par client / département",
        "clients.title": "Clients", "clients.new": "Nouveau client",
        "clients.edit": "Modifier le client", "clients.name": "Nom",
        "clients.color": "Couleur d'identification",
        "clients.placeholder": "Ex. Client Acme / Marketing",
        "clients.save": "Enregistrer", "clients.cancel": "Annuler",
        "clients.empty_title": "Aucun client",
        "clients.empty_message": "Créez votre premier client ou département pour organiser vos heures.",
        "clients.add": "Nouveau client",
        "clients.projects_one": "projet", "clients.projects_many": "projets",
        "projects.title": "Projets", "projects.new": "Nouveau projet",
        "projects.edit": "Modifier le projet", "projects.name": "Nom",
        "projects.clients_section": "Clients / Départements",
        "projects.description": "Description (optionnel)",
        "projects.description_hint": "Détails du projet…",
        "projects.weekly_hours": "Heures hebdomadaires assignées",
        "projects.color": "Couleur d'identification",
        "projects.save": "Enregistrer", "projects.cancel": "Annuler",
        "projects.empty_title": "Aucun projet",
        "projects.empty_no_clients": "Créez d'abord un client, puis assignez-lui des projets.",
        "projects.empty_message": "Créez votre premier projet et assignez-le à un client.",
        "projects.add": "Nouveau projet", "projects.no_client": "Aucun client",
        "projects.per_week": "Heures/semaine",
        "projects.create_client_first": "Créez d'abord un client dans Paramètres.",
        "projects.selected": "Sélectionnés :",
        "projects.placeholder": "Ex. Refonte du site",
        "stats.no_data": "Aucune donnée",
        "stats.no_data_message": "Aucun enregistrement dans cette période.",
        "stats.hours_by": "Heures par", "stats.client": "Client",
        "stats.project": "Projet",
        "stats.evolution": "Évolution des heures travaillées",
        "stats.current_period": "Période actuelle",
        "period.week": "Semaine", "period.month": "Mois", "period.year": "Année",
        "period.picker": "Période",
        "lang.title": "Langue",
        "common.missing_format": "Reste {0}",
    ]

    // MARK: Deutsch
    static let de: [String: String] = [
        "tab.home": "Startseite", "tab.week": "Woche", "tab.records": "Einträge",
        "tab.charts": "Diagramme", "tab.settings": "Einstellungen",
        "dash.timer": "Stoppuhr", "dash.save": "Speichern",
        "dash.start": "Starten", "dash.current_week": "Aktuelle Woche",
        "dash.by_client": "Nach Kunde / Abteilung",
        "dash.no_hours": "Du hast diese Woche noch keine Stunden eingetragen.",
        "dash.assigned": "Zugewiesen", "dash.worked": "Gearbeitet",
        "dash.remaining": "Verbleibend", "dash.excess": "Überschuss",
        "dash.progress": "Fortschritt", "dash.record_hours": "Stunden erfassen",
        "week.summary": "Zusammenfassung", "week.calendar": "Kalender",
        "week.this_week": "Diese Woche", "week.back_to_today": "Zurück zu heute",
        "week.no_records_day": "Keine Einträge für diesen Tag.",
        "week.connect_google": "Google Calendar verbinden",
        "week.google_desc": "Sieh deine Ereignisse neben deinen Arbeitsstunden, ohne die App zu verlassen.",
        "week.connect_google_btn": "Mit Google verbinden",
        "week.loading": "Ereignisse werden geladen…",
        "week.readonly": "Nur Lesen",
        "week.readonly_desc": "Erweitere die Berechtigungen, um Ereignisse zu erstellen und zu bearbeiten.",
        "week.expand": "Erweitern",
        "week.all_day": "Ganztägig",
        "week.all_day_short": "Ganzer\nTag",
        "week.disconnect": "Google Calendar trennen",
        "week.no_events": "Keine Ereignisse diese Woche.",
        "cal.detail": "Ereignisdetails", "cal.close": "Schließen",
        "cal.edit": "Bearbeiten", "cal.delete": "Ereignis löschen",
        "cal.new": "Neues Ereignis", "cal.edit_title": "Ereignis bearbeiten",
        "cal.title_placeholder": "Ereignistitel",
        "cal.cancel": "Abbrechen", "cal.create": "Erstellen",
        "cal.save": "Speichern",
        "cal.start": "Beginn", "cal.end": "Ende", "cal.date": "Datum",
        "entries.empty_title": "Keine Einträge",
        "entries.empty_message": "Beginne damit, deine täglichen Arbeitsstunden zu erfassen.",
        "entries.record": "Stunden erfassen", "entries.delete": "Löschen",
        "entries.all_clients": "Alle Kunden",
        "entries.all_projects": "Alle Projekte",
        "entries.clear_filters": "Filter entfernen",
        "entries.unassigned": "Nicht zugewiesen",
        "form.date": "Datum", "form.day": "Tag",
        "form.hours": "Geleistete Stunden",
        "form.client": "Kunde / Abteilung",
        "form.create_client": "Erstelle zuerst einen Kunden in den Einstellungen.",
        "form.no_client": "Nicht zugewiesen", "form.project": "Projekt",
        "form.no_project": "Kein Projekt",
        "form.comment": "Kommentar (optional)",
        "form.comment_hint": "Notizen zur Arbeit…",
        "form.delete_entry": "Eintrag löschen",
        "form.new": "Neuer Eintrag", "form.edit": "Eintrag bearbeiten",
        "form.cancel": "Abbrechen", "form.save": "Speichern",
        "form.delete": "Löschen",
        "form.irreversible": "Diese Aktion kann nicht rückgängig gemacht werden.",
        "form.client_picker": "Kunde", "form.project_picker": "Projekt",
        "settings.organization": "Organisation",
        "settings.clients": "Kunden / Abteilungen",
        "settings.projects": "Projekte", "settings.hours_section": "Stunden",
        "settings.weekly_hours": "Wochenstunden", "settings.data": "Daten",
        "settings.export": "Einträge exportieren (CSV)",
        "settings.support": "Support", "settings.rate": "App bewerten",
        "settings.suggest": "Vorschlag senden",
        "settings.version": "Version",
        "settings.privacy": "Deine Daten werden nur auf diesem Gerät gespeichert.",
        "settings.language": "Sprache", "settings.language_section": "Sprache",
        "whours.title": "Wochenstunden", "whours.total": "Wochengesamt",
        "whours.per_week": "Stunden/Woche", "whours.daily": "Tagesziel",
        "whours.auto": "Auto", "whours.distribution": "Budgetverteilung",
        "whours.assigned": "Kunden zugewiesen", "whours.available": "Verfügbar",
        "whours.overassigned": "Du hast mehr Stunden zugewiesen als verfügbar.",
        "whours.no_assigned": "Nicht zugewiesen",
        "whours.footer": "Bei 0 wird automatisch als Wochengesamt ÷ 5 Tage berechnet.",
        "whours.by_client": "Nach Kunde / Abteilung",
        "clients.title": "Kunden", "clients.new": "Neuer Kunde",
        "clients.edit": "Kunden bearbeiten", "clients.name": "Name",
        "clients.color": "Erkennungsfarbe",
        "clients.placeholder": "z.B. Acme Kunde / Marketing",
        "clients.save": "Speichern", "clients.cancel": "Abbrechen",
        "clients.empty_title": "Keine Kunden",
        "clients.empty_message": "Erstelle deinen ersten Kunden oder deine erste Abteilung, um deine Stunden zu organisieren.",
        "clients.add": "Neuer Kunde",
        "clients.projects_one": "Projekt", "clients.projects_many": "Projekte",
        "projects.title": "Projekte", "projects.new": "Neues Projekt",
        "projects.edit": "Projekt bearbeiten", "projects.name": "Name",
        "projects.clients_section": "Kunden / Abteilungen",
        "projects.description": "Beschreibung (optional)",
        "projects.description_hint": "Projektdetails…",
        "projects.weekly_hours": "Zugewiesene Wochenstunden",
        "projects.color": "Erkennungsfarbe",
        "projects.save": "Speichern", "projects.cancel": "Abbrechen",
        "projects.empty_title": "Keine Projekte",
        "projects.empty_no_clients": "Erstelle zuerst einen Kunden und weise ihm dann Projekte zu.",
        "projects.empty_message": "Erstelle dein erstes Projekt und weise es einem Kunden zu.",
        "projects.add": "Neues Projekt", "projects.no_client": "Kein Kunde",
        "projects.per_week": "Stunden/Woche",
        "projects.create_client_first": "Erstelle zuerst einen Kunden in den Einstellungen.",
        "projects.selected": "Ausgewählt:",
        "projects.placeholder": "z.B. Website-Redesign",
        "stats.no_data": "Keine Daten",
        "stats.no_data_message": "Keine Einträge in diesem Zeitraum.",
        "stats.hours_by": "Stunden nach", "stats.client": "Kunde",
        "stats.project": "Projekt",
        "stats.evolution": "Entwicklung der Arbeitsstunden",
        "stats.current_period": "Aktueller Zeitraum",
        "period.week": "Woche", "period.month": "Monat", "period.year": "Jahr",
        "period.picker": "Zeitraum",
        "lang.title": "Sprache",
        "common.missing_format": "Noch {0}",
    ]

    // MARK: 中文
    static let zh: [String: String] = [
        "tab.home": "主页", "tab.week": "本周", "tab.records": "记录",
        "tab.charts": "图表", "tab.settings": "设置",
        "dash.timer": "计时器", "dash.save": "保存",
        "dash.start": "开始", "dash.current_week": "本周",
        "dash.by_client": "按客户/部门",
        "dash.no_hours": "本周暂无工时记录。",
        "dash.assigned": "已分配", "dash.worked": "已工作",
        "dash.remaining": "剩余", "dash.excess": "超额",
        "dash.progress": "进度", "dash.record_hours": "记录工时",
        "week.summary": "摘要", "week.calendar": "日历",
        "week.this_week": "本周", "week.back_to_today": "回到今天",
        "week.no_records_day": "今日暂无记录。",
        "week.connect_google": "连接 Google 日历",
        "week.google_desc": "在应用内同时查看日历事件和工作记录。",
        "week.connect_google_btn": "连接 Google",
        "week.loading": "加载事件中…",
        "week.readonly": "只读",
        "week.readonly_desc": "扩展权限以创建和编辑事件。",
        "week.expand": "扩展", "week.all_day": "全天",
        "week.all_day_short": "全天",
        "week.disconnect": "断开 Google 日历",
        "week.no_events": "本周无事件。",
        "cal.detail": "事件详情", "cal.close": "关闭",
        "cal.edit": "编辑", "cal.delete": "删除事件",
        "cal.new": "新建事件", "cal.edit_title": "编辑事件",
        "cal.title_placeholder": "事件标题",
        "cal.cancel": "取消", "cal.create": "创建", "cal.save": "保存",
        "cal.start": "开始", "cal.end": "结束", "cal.date": "日期",
        "entries.empty_title": "暂无记录",
        "entries.empty_message": "开始记录您每天的工作时间。",
        "entries.record": "记录工时", "entries.delete": "删除",
        "entries.all_clients": "所有客户", "entries.all_projects": "所有项目",
        "entries.clear_filters": "清除筛选", "entries.unassigned": "未分配",
        "form.date": "日期", "form.day": "日",
        "form.hours": "工作时长",
        "form.client": "客户/部门",
        "form.create_client": "请先在设置中创建客户。",
        "form.no_client": "未分配", "form.project": "项目",
        "form.no_project": "无项目",
        "form.comment": "备注（可选）",
        "form.comment_hint": "工作备注…",
        "form.delete_entry": "删除记录",
        "form.new": "新建记录", "form.edit": "编辑记录",
        "form.cancel": "取消", "form.save": "保存",
        "form.delete": "删除",
        "form.irreversible": "此操作无法撤销。",
        "form.client_picker": "客户", "form.project_picker": "项目",
        "settings.organization": "组织",
        "settings.clients": "客户/部门",
        "settings.projects": "项目", "settings.hours_section": "工时",
        "settings.weekly_hours": "每周工时", "settings.data": "数据",
        "settings.export": "导出记录 (CSV)",
        "settings.support": "支持", "settings.rate": "评价应用",
        "settings.suggest": "发送建议",
        "settings.version": "版本",
        "settings.privacy": "您的数据仅存储在此设备上。",
        "settings.language": "语言", "settings.language_section": "语言",
        "whours.title": "每周工时", "whours.total": "每周总计",
        "whours.per_week": "时/周", "whours.daily": "每日目标",
        "whours.auto": "自动", "whours.distribution": "预算分配",
        "whours.assigned": "分配给客户", "whours.available": "可用",
        "whours.overassigned": "已分配时数超出可用时数。",
        "whours.no_assigned": "未分配",
        "whours.footer": "为0时，自动计算为每周总计÷5天。",
        "whours.by_client": "按客户/部门",
        "clients.title": "客户", "clients.new": "新建客户",
        "clients.edit": "编辑客户", "clients.name": "名称",
        "clients.color": "标识颜色",
        "clients.placeholder": "例如：客户/部门",
        "clients.save": "保存", "clients.cancel": "取消",
        "clients.empty_title": "暂无客户",
        "clients.empty_message": "创建您的第一个客户或部门以组织工时。",
        "clients.add": "新建客户",
        "clients.projects_one": "个项目", "clients.projects_many": "个项目",
        "projects.title": "项目", "projects.new": "新建项目",
        "projects.edit": "编辑项目", "projects.name": "名称",
        "projects.clients_section": "客户/部门",
        "projects.description": "描述（可选）",
        "projects.description_hint": "项目详情…",
        "projects.weekly_hours": "分配的每周工时",
        "projects.color": "标识颜色",
        "projects.save": "保存", "projects.cancel": "取消",
        "projects.empty_title": "暂无项目",
        "projects.empty_no_clients": "请先创建客户，然后为其分配项目。",
        "projects.empty_message": "创建您的第一个项目并分配给客户。",
        "projects.add": "新建项目", "projects.no_client": "无客户",
        "projects.per_week": "时/周",
        "projects.create_client_first": "请先在设置中创建客户。",
        "projects.selected": "已选：",
        "projects.placeholder": "例如：网站重设计",
        "stats.no_data": "暂无数据",
        "stats.no_data_message": "该时段无记录。",
        "stats.hours_by": "按工时", "stats.client": "客户",
        "stats.project": "项目",
        "stats.evolution": "工时趋势",
        "stats.current_period": "当前周期",
        "period.week": "周", "period.month": "月", "period.year": "年",
        "period.picker": "周期",
        "lang.title": "语言",
        "common.missing_format": "剩余 {0}",
    ]

    // MARK: Italiano
    static let it: [String: String] = [
        "tab.home": "Inizio", "tab.week": "Settimana", "tab.records": "Registri",
        "tab.charts": "Grafici", "tab.settings": "Impostazioni",
        "dash.timer": "Cronometro", "dash.save": "Salva",
        "dash.start": "Avvia", "dash.current_week": "Settimana corrente",
        "dash.by_client": "Per cliente / reparto",
        "dash.no_hours": "Non hai ancora registrato ore questa settimana.",
        "dash.assigned": "Assegnate", "dash.worked": "Lavorate",
        "dash.remaining": "Rimanenti", "dash.excess": "Eccesso",
        "dash.progress": "Progresso", "dash.record_hours": "Registra ore",
        "week.summary": "Riepilogo", "week.calendar": "Calendario",
        "week.this_week": "Questa settimana",
        "week.back_to_today": "Torna a oggi",
        "week.no_records_day": "Nessun registro per questo giorno.",
        "week.connect_google": "Connetti Google Calendar",
        "week.google_desc": "Visualizza i tuoi eventi insieme alle ore di lavoro senza uscire dall'app.",
        "week.connect_google_btn": "Connetti con Google",
        "week.loading": "Caricamento eventi…",
        "week.readonly": "Solo lettura",
        "week.readonly_desc": "Espandi i permessi per creare e modificare eventi.",
        "week.expand": "Espandi", "week.all_day": "Tutto il giorno",
        "week.all_day_short": "Tutto\nil giorno",
        "week.disconnect": "Disconnetti Google Calendar",
        "week.no_events": "Nessun evento questa settimana.",
        "cal.detail": "Dettaglio evento", "cal.close": "Chiudi",
        "cal.edit": "Modifica", "cal.delete": "Elimina evento",
        "cal.new": "Nuovo evento", "cal.edit_title": "Modifica evento",
        "cal.title_placeholder": "Titolo evento",
        "cal.cancel": "Annulla", "cal.create": "Crea", "cal.save": "Salva",
        "cal.start": "Inizio", "cal.end": "Fine", "cal.date": "Data",
        "entries.empty_title": "Nessun registro",
        "entries.empty_message": "Inizia a registrare le ore che lavori ogni giorno.",
        "entries.record": "Registra ore", "entries.delete": "Elimina",
        "entries.all_clients": "Tutti i clienti",
        "entries.all_projects": "Tutti i progetti",
        "entries.clear_filters": "Rimuovi filtri",
        "entries.unassigned": "Non assegnato",
        "form.date": "Data", "form.day": "Giorno",
        "form.hours": "Ore lavorate",
        "form.client": "Cliente / Reparto",
        "form.create_client": "Crea prima un cliente in Impostazioni.",
        "form.no_client": "Non assegnato", "form.project": "Progetto",
        "form.no_project": "Nessun progetto",
        "form.comment": "Commento (facoltativo)",
        "form.comment_hint": "Note sul lavoro…",
        "form.delete_entry": "Elimina registro",
        "form.new": "Nuovo registro", "form.edit": "Modifica registro",
        "form.cancel": "Annulla", "form.save": "Salva",
        "form.delete": "Elimina",
        "form.irreversible": "Questa azione non può essere annullata.",
        "form.client_picker": "Cliente", "form.project_picker": "Progetto",
        "settings.organization": "Organizzazione",
        "settings.clients": "Clienti / Reparti",
        "settings.projects": "Progetti", "settings.hours_section": "Ore",
        "settings.weekly_hours": "Ore settimanali", "settings.data": "Dati",
        "settings.export": "Esporta registri (CSV)",
        "settings.support": "Supporto", "settings.rate": "Valuta l'app",
        "settings.suggest": "Invia suggerimento",
        "settings.version": "Versione",
        "settings.privacy": "I tuoi dati vengono salvati solo su questo dispositivo.",
        "settings.language": "Lingua", "settings.language_section": "Lingua",
        "whours.title": "Ore settimanali", "whours.total": "Totale settimanale",
        "whours.per_week": "Ore/settimana", "whours.daily": "Obiettivo giornaliero",
        "whours.auto": "Automatico", "whours.distribution": "Distribuzione budget",
        "whours.assigned": "Assegnate ai clienti", "whours.available": "Disponibili",
        "whours.overassigned": "Hai assegnato più ore di quelle disponibili.",
        "whours.no_assigned": "Non assegnato",
        "whours.footer": "A 0, calcolato automaticamente come totale settimanale ÷ 5 giorni.",
        "whours.by_client": "Per cliente / reparto",
        "clients.title": "Clienti", "clients.new": "Nuovo cliente",
        "clients.edit": "Modifica cliente", "clients.name": "Nome",
        "clients.color": "Colore identificativo",
        "clients.placeholder": "Es. Cliente Acme / Marketing",
        "clients.save": "Salva", "clients.cancel": "Annulla",
        "clients.empty_title": "Nessun cliente",
        "clients.empty_message": "Crea il tuo primo cliente o reparto per organizzare le ore.",
        "clients.add": "Nuovo cliente",
        "clients.projects_one": "progetto", "clients.projects_many": "progetti",
        "projects.title": "Progetti", "projects.new": "Nuovo progetto",
        "projects.edit": "Modifica progetto", "projects.name": "Nome",
        "projects.clients_section": "Clienti / Reparti",
        "projects.description": "Descrizione (facoltativa)",
        "projects.description_hint": "Dettagli del progetto…",
        "projects.weekly_hours": "Ore settimanali assegnate",
        "projects.color": "Colore identificativo",
        "projects.save": "Salva", "projects.cancel": "Annulla",
        "projects.empty_title": "Nessun progetto",
        "projects.empty_no_clients": "Prima crea un cliente, poi assegnagli dei progetti.",
        "projects.empty_message": "Crea il tuo primo progetto e assegnalo a un cliente.",
        "projects.add": "Nuovo progetto", "projects.no_client": "Nessun cliente",
        "projects.per_week": "Ore/settimana",
        "projects.create_client_first": "Crea prima un cliente in Impostazioni.",
        "projects.selected": "Selezionati:",
        "projects.placeholder": "Es. Redesign sito web",
        "stats.no_data": "Nessun dato",
        "stats.no_data_message": "Nessun registro in questo periodo.",
        "stats.hours_by": "Ore per", "stats.client": "Cliente",
        "stats.project": "Progetto",
        "stats.evolution": "Evoluzione delle ore lavorate",
        "stats.current_period": "Periodo corrente",
        "period.week": "Settimana", "period.month": "Mese", "period.year": "Anno",
        "period.picker": "Periodo",
        "lang.title": "Lingua",
        "common.missing_format": "Mancano {0}",
    ]

    // MARK: Català
    static let ca: [String: String] = [
        "tab.home": "Inici", "tab.week": "Setmana", "tab.records": "Registres",
        "tab.charts": "Gràfics", "tab.settings": "Configuració",
        "dash.timer": "Cronòmetre", "dash.save": "Desar",
        "dash.start": "Iniciar", "dash.current_week": "Setmana actual",
        "dash.by_client": "Per client / departament",
        "dash.no_hours": "Encara no has registrat hores aquesta setmana.",
        "dash.assigned": "Assignades", "dash.worked": "Treballades",
        "dash.remaining": "Restants", "dash.excess": "Excés",
        "dash.progress": "Progrés", "dash.record_hours": "Registrar hores",
        "week.summary": "Resum", "week.calendar": "Calendari",
        "week.this_week": "Aquesta setmana",
        "week.back_to_today": "Tornar a avui",
        "week.no_records_day": "Cap registre per a aquest dia.",
        "week.connect_google": "Connecta Google Calendar",
        "week.google_desc": "Visualitza els teus esdeveniments amb les hores de treball sense sortir de l'app.",
        "week.connect_google_btn": "Connecta amb Google",
        "week.loading": "Carregant esdeveniments…",
        "week.readonly": "Només lectura",
        "week.readonly_desc": "Amplia els permisos per crear i editar esdeveniments.",
        "week.expand": "Ampliar", "week.all_day": "Tot el dia",
        "week.all_day_short": "Tot\nel dia",
        "week.disconnect": "Desconnecta Google Calendar",
        "week.no_events": "Cap esdeveniment aquesta setmana.",
        "cal.detail": "Detall de l'esdeveniment", "cal.close": "Tancar",
        "cal.edit": "Editar", "cal.delete": "Eliminar esdeveniment",
        "cal.new": "Nou esdeveniment", "cal.edit_title": "Editar esdeveniment",
        "cal.title_placeholder": "Títol de l'esdeveniment",
        "cal.cancel": "Cancel·lar", "cal.create": "Crear", "cal.save": "Desar",
        "cal.start": "Inici", "cal.end": "Fi", "cal.date": "Data",
        "entries.empty_title": "Cap registre",
        "entries.empty_message": "Comença a registrar les hores que treballes cada dia.",
        "entries.record": "Registrar hores", "entries.delete": "Esborrar",
        "entries.all_clients": "Tots els clients",
        "entries.all_projects": "Tots els projectes",
        "entries.clear_filters": "Treure filtres",
        "entries.unassigned": "Sense assignar",
        "form.date": "Data", "form.day": "Dia",
        "form.hours": "Hores treballades",
        "form.client": "Client / Departament",
        "form.create_client": "Crea primer un client a Configuració.",
        "form.no_client": "Sense assignar", "form.project": "Projecte",
        "form.no_project": "Sense projecte",
        "form.comment": "Comentari (opcional)",
        "form.comment_hint": "Notes sobre el treball…",
        "form.delete_entry": "Eliminar registre",
        "form.new": "Nou registre", "form.edit": "Editar registre",
        "form.cancel": "Cancel·lar", "form.save": "Desar",
        "form.delete": "Eliminar",
        "form.irreversible": "Aquesta acció no es pot desfer.",
        "form.client_picker": "Client", "form.project_picker": "Projecte",
        "settings.organization": "Organització",
        "settings.clients": "Clients / Departaments",
        "settings.projects": "Projectes", "settings.hours_section": "Hores",
        "settings.weekly_hours": "Hores setmanals", "settings.data": "Dades",
        "settings.export": "Exportar registres (CSV)",
        "settings.support": "Suport", "settings.rate": "Valorar l'app",
        "settings.suggest": "Enviar suggeriment",
        "settings.version": "Versió",
        "settings.privacy": "Les teves dades es guarden únicament en aquest dispositiu.",
        "settings.language": "Idioma", "settings.language_section": "Idioma",
        "whours.title": "Hores setmanals", "whours.total": "Total setmanal",
        "whours.per_week": "Hores/setmana", "whours.daily": "Objectiu diari",
        "whours.auto": "Automàtic", "whours.distribution": "Repartiment del pressupost",
        "whours.assigned": "Assignades als clients", "whours.available": "Disponibles",
        "whours.overassigned": "Has assignat més hores de les disponibles.",
        "whours.no_assigned": "Sense assignar",
        "whours.footer": "A 0, es calcula automàticament com el total setmanal ÷ 5 dies.",
        "whours.by_client": "Per client / departament",
        "clients.title": "Clients", "clients.new": "Nou client",
        "clients.edit": "Editar client", "clients.name": "Nom",
        "clients.color": "Color identificatiu",
        "clients.placeholder": "Ex. Client Acme / Màrqueting",
        "clients.save": "Desar", "clients.cancel": "Cancel·lar",
        "clients.empty_title": "Cap client",
        "clients.empty_message": "Crea el teu primer client o departament per organitzar les hores.",
        "clients.add": "Nou client",
        "clients.projects_one": "projecte", "clients.projects_many": "projectes",
        "projects.title": "Projectes", "projects.new": "Nou projecte",
        "projects.edit": "Editar projecte", "projects.name": "Nom",
        "projects.clients_section": "Clients / Departaments",
        "projects.description": "Descripció (opcional)",
        "projects.description_hint": "Detalls del projecte…",
        "projects.weekly_hours": "Hores setmanals assignades",
        "projects.color": "Color identificatiu",
        "projects.save": "Desar", "projects.cancel": "Cancel·lar",
        "projects.empty_title": "Cap projecte",
        "projects.empty_no_clients": "Crea primer un client i després assigna-li projectes.",
        "projects.empty_message": "Crea el teu primer projecte i assigna'l a un client.",
        "projects.add": "Nou projecte", "projects.no_client": "Sense client",
        "projects.per_week": "Hores/setmana",
        "projects.create_client_first": "Crea primer un client a Configuració.",
        "projects.selected": "Seleccionats:",
        "projects.placeholder": "Ex. Redisseny web",
        "stats.no_data": "Sense dades",
        "stats.no_data_message": "Cap registre en aquest període.",
        "stats.hours_by": "Hores per", "stats.client": "Client",
        "stats.project": "Projecte",
        "stats.evolution": "Evolució de les hores treballades",
        "stats.current_period": "Període actual",
        "period.week": "Setmana", "period.month": "Mes", "period.year": "Any",
        "period.picker": "Període",
        "lang.title": "Idioma",
        "common.missing_format": "Falten {0}",
    ]
}
